version: '3.10'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web/static
      - media_data:/app/media
    environment:
      - SECRET_KEY=samplekey
      - DEBUG=1
    networks:
      - my_network

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media/
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - app
    networks:
      - my_network

volumes:
  static_data:
  media_data:

networks:
  my_network:
    driver: bridge